### PR TITLE
Use docker containers for Travis builds.

### PR DESCRIPTION
**Pull request by benpatterson**
Blog post here: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

### CODE REVIEW

**Comment by clintonb** [comment]
Assuming caching is now available for public repos, you might also look into caching the pip, node, and bower dependencies.

:+1:

**Comment by benpatterson** [comment]
@clintonb good call on the cache. I put that in as well.

**Comment by benpatterson** [comment]
@jzoldak @clytwynec could I get a 2nd set of eyes on this change?

**Comment by clytwynec** [comment]
Not really an issue with this PR, but it feels like there should be a more obviously named setting for using containers than `sudo: false`.   Thanks for adding the comment above it to point out what it's really doing.

:+1:

**Comment by benpatterson** [comment]
Agreed, @clytwynec

**Pull request merged**
