### PR TITLE
[BD-6] Python 3.8 in travis tests

### PR DESCRIPTION
**Pull request by morenol**
## Description
* Remove python 2.7 and 3.6 tests and add python 3.5 and 3.8 tests
* Switch tests from nose to pytest
* Change setup.py to take requirements from requirements/base.in (OEP-18)
* Remove constraints of test requirements (except by httpretty, using the same constraint of edx-platform)
* Change pep8 and pep257 with pycodestyle and pydocstyle
* Quality fixes 
* Create a new release with the new classifiers
* Separate quality tests and python tests in travis/tox

## Reviewers
- [ ] @ericfab170
- [ ] @awais786

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-4464](https://openedx.atlassian.net/browse/OSPR-4464) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by morenol** [comment]
> shouldn't we run quality against python 3.8 as well? while we're at it.

Good catch, I don't understand why it was not running. But I made a change and now it is running

**Comment by edx-webhook** [comment]
@morenol 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-data-api-client&entry.867055334=https://github.com/edx/edx-analytics-data-api-client/pull/64&entry.1484655318=https://github.com/morenol&entry.752974735=2020-05-05+20:06&entry.1917517419=2020-05-08+19:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by mraarif** [comment]
@morenol looks like the last release to PyPI failed because of the deploy section in `.travis.yml` has a condition for `python: 3.5` and there were two builds available against python 3.5, one of them uploaded successfully and other one failed, you should also specify the environment in the deploy section (something like this)
`on:
    tags: true
    python: 3.5
    condition: "$TOXENV = quality"`

**Comment by morenol** [comment]
Got it

**Pull request merged**
