### PR TITLE
INCR-20: Add tox.ini

### PR DESCRIPTION
**Pull request by annagav**
Create an appropriate tox.ini file for running tests in Python 2.7 and 3.6

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @annagav! I've created [OSPR-3023](https://openedx.atlassian.net/browse/OSPR-3023) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@annagav  Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions.

**Comment by pdpinch** [comment]
@natabene Anna is an employee of MIT Open Learning. I think her contributions should be covered by the MIT agreement.

**Comment by natabene** [comment]
@pdpinch Thanks for letting me know, I will add Anna. @annagav Can you please give me your email address so I can add you to our contributor list?

**Comment by annagav** [comment]
@natabene My email is my username at mit.edu.

**Comment by natabene** [comment]
@annagav Thank you, I have added you to our contributors list, and we can review your code going on forward.  Please let me know once it is ready to be looked at.

**Comment by annagav** [comment]
@natabene, thanks! This PR should be ready for review.

**Comment by natabene** [comment]
@annagav Do you want to look into why the test is failing  first?

**Comment by annagav** [comment]
@natabene, It says: `The program 'tox' is currently not installed. To run 'tox' please ask your administrator to install the package 'python-tox'`

**Comment by natabene** [comment]
@edx/incr-reviewers  Can you give this a look?

**Comment by estute** [comment]
@annagav tox is not installed natively on Travis CI, and we haven't specified it as a testing dependency this repo. Could you add `tox` and `tox-travis` to `requirement.txt` and rerun the tests? You can use the versions we pinned here: https://github.com/edx/bok-choy/blob/master/requirements/travis.txt

**Comment by estute** [comment]
@annagav - looks good. One last thing: could you make sure to whitelist `make` and squash the commits? Tox runs the tests, but is throwing an error about the test command

**Comment by annagav** [comment]
@estute I addressed the comments, thanks!

**Comment by natabene** [comment]
@estute Is this good to go now?

**Comment by edx-webhook** [comment]
@annagav 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-data-api-client&entry.867055334=https://github.com/edx/edx-analytics-data-api-client/pull/48&entry.1484655318=https://github.com/annagav&entry.752974735=2019-01-29+21:53&entry.1917517419=2019-03-15+14:04&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
