### PR TITLE
upgraded pylint to make it run in python 3.6

### PR DESCRIPTION
**Pull request by mulka**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mulka! I've created [OSPR-3412](https://openedx.atlassian.net/browse/OSPR-3412) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@mulka Thank you for your contribution, please let me know once all checks are green.

**Comment by jmbowman** [comment]
It looks like the new version of pylint added several new checks that we're running afoul of.  `isort` should be able to fix at least some of those automatically.

**Comment by mulka** [comment]
@natabene all checks are green

**Comment by natabene** [comment]
@jmbowman This is ready for your review.

**Comment by edx-webhook** [comment]
@mulka 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-data-api-client&entry.867055334=https://github.com/edx/edx-analytics-data-api-client/pull/53&entry.1484655318=https://github.com/mulka&entry.752974735=2019-05-09+07:35&entry.1917517419=2019-05-20+15:05&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by mulka** [comment]
@jmbowman You're welcome!

**Pull request merged**
