### PR TITLE
[ENT-979] Add Enterprise Data API client.

### PR DESCRIPTION
**Pull request by UmanShahzad**
This adds the Enterprise Data API client that will allow easy access to the Enterprise Enrollments endpoint in the Analytics Data API server.

I'm not sure how to explicitly test this, but you can ensure that the URL we call here is the same as the one defined [here](https://github.com/edx/edx-enterprise-data/blob/master/enterprise_data/api/v0/urls.py#L11-L15).

**Note**: Currently this assumes the Enterprise API will take in a plain token. But the view associated with `/enterprise/{}/enrollments/` expects JWT. I may have to update this to allow using JWT, or update the view to use token authentication as fallback.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @UmanShahzad! I've created [OSPR-2402](https://openedx.atlassian.net/browse/OSPR-2402) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-analytics-data-api-client/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by UmanShahzad** [comment]
@georgebabey Do see my 'note' above about JWT vs. Token. I don't know if there are business reasons behind using JWT, but all clients in this repo use token authentication, so maybe we can allow the Enterprise Enrollments endpoint in the data API to fallback to token auth?

**Comment by UmanShahzad** [comment]
Nevermind, we won't be using this.

**Comment by edx-webhook** [comment]
Although this pull request is already closed, I've created [OSPR-5498](https://openedx.atlassian.net/browse/OSPR-5498) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks.

**Pull request closed without merging**
