### PR TITLE
Upgrade API client tests to new answer_dist schema

### PR DESCRIPTION
**Pull request by dylanrhodes**
This is a fairly minor PR to accompany the open ones against the analytics-api and pipeline which include the count of choices for students' first attempts at problems.  It changes the format of the test data used by the client's unit tests to mock the API in order to bring it in line with the new schema.  Feedback and comments are welcome @dcadams @clintonb @mulby

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dylanrhodes! I've created [OSPR-413](https://openedx.atlassian.net/browse/OSPR-413) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by clintonb** [comment]
:+1:

**Comment by sarina** [comment]
@dylanrhodes @clintonb @mulby for this and the other two PRs you've opened, they should be reviewed in our product triage meeting by Victor. Our next product triage meeting is Wednesday next week.

**Comment by sarina** [comment]
@lamagnifica FYI there will be doc impact here, I suspect (for these three PRs) - see OSPR-413, OSPR-414, and OSPR-415 tickets.

**Comment by lamagnifica** [comment]
@mhoeber, no impact on the research guide or Insights guide at this time. Effect on the API guide TBD.

**Pull request merged**
